App_Login/urls.py
from django.urls import path
from . import views

app_name = "App_Login"


urlpatterns = [
    path('signup/', views.sign_up, name='sign_up'),
    path('login/', views.login_page, name='login'),
    path('edit/', views.edit_profile, name='edit'),
    path('logout/', views.logout_user, name='logout'),
    path('profile', views.profile, name='profile'),
    path('user/<username>/', views.user, name='user'),
    path('follow/<username>/', views.follow, name='follow'),
    path('unfollow/<username>/', views.unfollow, name='unfollow'),
]

App_Post/urls.py
from django.urls import path
from App_Post import views

app_name = 'App_Post'

urlpatterns = [
    path("", views.home, name='home'),
    path('liked/<pk>/', views.liked, name='liked'),
    path('unliked/<pk>/', views.unliked, name='unliked'),
]

My_Social_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from App_Post import views
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('post/', include('App_Post.urls')),
    path('', views.home, name='home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
    <title>{% block title_block %} Social {% endblock %}</title>

        {% block css_block %}

        {% endblock %}
</head>

<body>
    <div class="container" style="padding-top:20px">
        {% block body_block %}

        {% endblock %}
    </div>
</body>

</html>

templates/navbar.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/7bcf9a3d26.js" crossorigin="anonymous"></script>
    <title>{% block title_block %} Social {% endblock %}</title>

        {% block css_block %}

        {% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'App_Post:home' %}">Home</a>
              </li>
              
              <li class="nav-item">
                {% if user.user_profile.profile_pic %}
                <a class="nav-link" href="{% url 'App_Login:profile' %}"><img src="/media/{{user.user_profile.profile_pic}}" width="20px" 
                    alt="" class="rounded-circle"></a>
                {% else %}
                <a class="nav-link" href="{% url 'App_Login:profile' %}"><img src="/media/profile.jpg" alt="" width="20px" class="rounded-circle"></a>
                {% endif %}
              </li>
              &nbsp; &nbsp;
              <form class="d-flex" method="GET">
                <input class="form-control me-2" type="text" name="search" placeholder="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'App_Login:logout' %}">Logout</a>
              </li>
        </ul>
    </nav>
    <div class="container" style="padding-top:30px">
        {% block body_block %}

        {% endblock %}
    </div>
</body>

</html>